# TUGAS 3

## **Catatan Kelas**

In [16]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
print(B)
print(C)

[[ 2 -3  4]
 [-1 -2  1]
 [ 4 -5  7]]
[[-2  1 -6]
 [ 4 -3  9]]


In [17]:
# Cara buat matrix dengan cepat menggunakan bilangan yang random

AAA = np.random.randint(10,size=(3,3))
print(AAA)

[[1 8 4]
 [5 7 9]
 [4 3 7]]


### *Operasi-operasi Matrik*
1. Matriks dalam bentuk apapun dapat dikalikan dengan skalar *c, d*.

In [18]:
c = 2
d = 4
e = c + d
G = (c+d)*A
H = (c*A) + (d*A)
print('e =', e)
print('G =', G)
print('H =', H)

e = 6
G = [[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]
H = [[  6  18 -12]
 [ 12  24  -6]
 [ 18 -36  48]]


2. Matriks yang ukurannya sama bisa dijumlahkan. Hasilnya adalah semua elemen yang bersesuaian dan ditambah dalam bentuk.

In [19]:
K = A + B
#L = A + C
print('K =', K)
#print('L =', L)

K = [[  3   0   2]
 [  1   2   0]
 [  7 -11  15]]


3. Jika banyaknya kolom dari matrix ***A*** adalah sama dengan banyaknya baris matrik ***B***, maka kedua matrik dapat dikalikan dalam bentuk perkalian ***A,B***. Dengan jumlah baris yang mengikuti matriks A dan kolom mengikuti matriks B.

In [20]:
#Cara menentukan ukuran matriks:
#  namamatriks.shape
print(C.shape)

#Cara menentukan jumlah baris:
#  namamatriks.shape[0]
print(C.shape[0])

#Cara menentukan jumlah kolom:
#  namamatriks.shape[1]
print(C.shape[1])

(2, 3)
2
3


In [21]:
print(A*B)

[[ 2 -9 -8]
 [-2 -8 -1]
 [12 30 56]]


In [22]:
print(A@B)

[[ -9   1  -7]
 [ -4  -9   5]
 [ 44 -37  62]]


In [23]:
print(A@C)
# Tidak bisa dioperasikan karena jumlah kolom A tidak sama dengan jumlah baris C. Sehingga terjadi error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [26]:
import sympy as sy
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z =\
sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real=True)

In [27]:
AA = sy.Matrix([[a, b, c], [d, e, f]])
AA + AA

Matrix([
[2*a, 2*b, 2*c],
[2*d, 2*e, 2*f]])

### *Matriks Transpose*

(Baris jadi kolom, dan sebaliknya)

lambang transpose matriks A adalah $A^T$

note : Matriks Covarian adalah matriks awal dikali matriks transposenya.

In [ ]:
A_T = A.transpose()
print(A)
print(" ")
print(A_T)

[[ 1  3 -2]
 [ 2  4 -1]
 [ 3 -6  8]]
 
[[ 1  2  3]
 [ 3  4 -6]
 [-2 -1  8]]


In [ ]:
C_T = C.transpose()
CoV = C*C_T
print(CoV.shape)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
A = np.array([[10,3,-2],[2,4,-1],[3,-6,8]])
print(A)
print(" ")

A_T = A.transpose()
print(A_T)

[[10  3 -2]
 [ 2  4 -1]
 [ 3 -6  8]]
 
[[10  2  3]
 [ 3  4 -6]
 [-2 -1  8]]


In [ ]:
import numpy as np
A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1,-6],[4,-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])
t = A*B*D
print(t)
print(" ")
tt = t.transpose()
print(tt)
print(" ")
print(" ")
a = A.transpose()
b = B.transpose()
dd = D.transpose()
print(a*b*dd)
print(" ")
print(" ")
abd = (A+B)*D
ABD = abd.transpose()
print(ABD)
print(" ")
print(" ")
abc = (A+B)*C
ABC = abc.transpose()
print(ABC)

[[  4 -72 -16]
 [  8 -40  -6]
 [ 84 -90  56]]
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
 
[[  4   8  84]
 [-72 -40 -90]
 [-16  -6  56]]
 
 
[[ 6 -4 49]
 [ 0 10 33]
 [ 4  0 15]]
 
 


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

### *Matriks Elementer*

Matriks elementer adalah matriks yang dapat diperoleh dari satu operasi baris elementer pada suatu matriks identitas.

In [34]:
Aa = sy.randMatrix(3, percent=80); Aa

Matrix([
[ 0, 75, 0],
[ 4, 78, 6],
[87,  7, 3]])

In [28]:
E = sy.Matrix([[0,1,0],[1,0,0],[0,0,1]]);E

Matrix([
[0, 1, 0],
[1, 0, 0],
[0, 0, 1]])

In [29]:
E*A

Matrix([
[2,  4, -1],
[1,  3, -2],
[3, -6,  8]])

## **Tugas Mengalikan Matriks dengan Kode**

In [36]:
import numpy as np

A = np.array([[1,3,-2],[2,4,-1],[3,-6,8]])
B = np.array([[2,-3,4],[-1,-2,1],[4,-5,7]])
C = np.array([[-2,1],[-6,4],[-3,9]])
D = np.array([[2,8,2],[-4,5,6],[7,-3,1]])

# Mengalikan matriks A dengan matriks B
AB = np.dot(A, B)

# Mengalikan matriks AB dengan matriks C
ABC = np.dot(AB, C)

# Mengalikan matriks A dengan matriks D
AD = np.dot(A, D)

# Mengalikan matriks AB dengan matriks D
ABD = np.dot(AB, D)

# Mengalikan matriks A dengan matriks B, lalu hasilnya dikalikan dengan matriks D
ABD_alt = np.dot(A, np.dot(B, D))

# Menampilkan hasil
print("Hasil perkalian matriks A dengan matriks B:")
print(AB)
print("\nHasil perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks C:")
print(ABC)
print("\nHasil perkalian matriks A dengan matriks D:")
print(AD)
print("\nHasil perkalian matriks A dan B, lalu hasilnya dikalikan dengan matriks D:")
print(ABD)
print("\nHasil alternatif perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks D:")
print(ABD_alt)

Hasil perkalian matriks A dengan matriks B:
[[ -9   1  -7]
 [ -4  -9   5]
 [ 44 -37  62]]

Hasil perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks C:
[[ 33 -68]
 [ 47   5]
 [-52 454]]

Hasil perkalian matriks A dengan matriks D:
[[-24  29  18]
 [-19  39  27]
 [ 86 -30 -22]]

Hasil perkalian matriks A dan B, lalu hasilnya dikalikan dengan matriks D:
[[-71 -46 -19]
 [ 63 -92 -57]
 [670 -19 -72]]

Hasil alternatif perkalian matriks A dengan matriks B, lalu dikalikan dengan matriks D:
[[-71 -46 -19]
 [ 63 -92 -57]
 [670 -19 -72]]
